### ISSUE TITLE
Would be nice to create Cucumber test to check VM converged

### ISSUE THREAD

**Issue by esciara** [sous-chefs/confluence#10]
Could use https://github.com/esciara/wonderstuff/tree/6bbbd847fc71258e09e92070df67497b109a5a51/features/step_definitions as an example but without using `leibniz` (for more info about why, see https://github.com/esciara/wonderstuff#tests).
Could use [`faraday`](https://github.com/lostisland/faraday) to check that the title of the home page is "Confluence Setup Wizard - Confluence".
Without `leibniz`, `cucumber` tests would have to be run from inside the VM, meaning that ip to use might be that of `localhost`. But if I remember correctly, Confluence will automatically redirect to the full name of the machine... So might need to add an entry to `/etc/hosts/` to make it work.

**Comment by esciara** [comment]
@bflad I have had it to work using `busser-cucumber` but I am still having some ugly code I do not know how to change.

Here is the gist with all relevant files: https://gist.github.com/esciara/ba18b442164f16942a79

I managed to have the `cucumber` test to check the home page but I need to know the IP address of the VM... and it has two. The current code is guessing that the good IP is the second one.... Not pretty, I know.

``` ruby
 @local_ip = Socket.ip_address_list[2].ip_address
```

Don't really know where else I could get the IP, either on the system of in somewhere in the configurations. I need a second opinion.

**Comment by bflad** [comment]
This looks really interesting. I apologize I haven't had time the last few days to look at these yet, but I'll start digging in shortly.

**Comment by esciara** [comment]
Doing this exercise makes me realise that it would be good to have an equivalent of `leibniz` but that would rather work like a plugin to `test-kitchen`, so that it runs `cucumber` tests from outside the box whenever `kitchen verify` or `kitchen test` are called... will look around on how this is possible.

**Comment by esciara** [comment]
I have advanced on the subject if you might be interested...

**Comment by legal90** [comment]
It was implemented via ServerSpec: #69
