### ISSUE TITLE
Attribute change in latest Apache2 cookbook

### ISSUE THREAD

**Issue by xlongxl** [sous-chefs/confluence#102]
The `['listen_ports']` attribute has been renamed to `['listen']` in the latest Apache2 cookbook (V 3.2.0), and it is now an array of 'address:port' strings: https://github.com/svanzoest-cookbooks/apache2/pull/378

Could you update the apache2 recipe? https://github.com/parallels-cookbooks/confluence/blob/11f5dfb119c0fa090f81aef3952ed1bf945dd368/recipes/apache2.rb#L20-L21
Thanks!

**Comment by mrjcleaver** [comment]
It'd be nice to have a workaround for the latest version. I'm stumped  :(

**Comment by legal90** [comment]
Fixed by #103
