### ISSUE TITLE
Support for system properties?

### ISSUE THREAD

**Issue by mrjcleaver** [sous-chefs/confluence#113]
Do we have support to set https://confluence.atlassian.com/doc/configuring-system-properties-168002854.html e.g. for https://confluence.atlassian.com/doc/hiding-the-people-directory-196816.html ?

**Comment by legal90** [comment]
Yes, it could be done with attribute `['confluence']['jvm']['java_opts']`
https://github.com/parallels-cookbooks/confluence/blob/master/attributes/default.rb#L66

In the `setenv.sh` this attribute will be rendered here:
https://github.com/parallels-cookbooks/confluence/blob/master/templates/default/setenv.sh.erb#L53
