### ISSUE TITLE
Unable to log into Confluence after build

### ISSUE THREAD

**Issue by jsibo** [sous-chefs/confluence#121]
Setting up 2 separate servers: webapp & db using this cookbook. After going through the manual configuration steps: putting in the license, setting up the external db, and creating an internal user... I am then unable to log into the instance with the aforementioned internally created user. No errors appear - it just redirects to the same page. Thoughts?

**Comment by legal90** [comment]
Hi @jsibo,
Confluence setup and user account creating are out of this cookbook's context. 
I'd recommend looking at the following log files:
- `/var/atlassian/application-data/confluence/logs/atlassian-confluence.log`
- `/opt/atlassian/confluence/logs/catalina.out`

and refer to Atlassian help resources: https://www.atlassian.com/resources/support
