### ISSUE TITLE
Chef 12?

### ISSUE THREAD

**Issue by mrjcleaver** [sous-chefs/confluence#122]
What versions of Chef is this known to work with?

**Comment by legal90** [comment]
Our TravisCI builds always test it with the latest Chef Client version. Currently it is 12.15.19
I also have a Confluence instance converged successfully with Chef Client 12.12.15

**Comment by legal90** [comment]
Feel free to file a new issue if you have any compatibility issues with previous versions of Chef Client.

P.s. I'm not sure we would support the previous major versions (Chef Client 11 and earlier), but we can manage to support at least 12.5+
