### ISSUE TITLE
Failing to start due to file permissions

### ISSUE THREAD

**Issue by nickpetrovic** [sous-chefs/confluence#125]
The application fails to start up due to permission issues applied to the application binaries. 

I have tested this by changing the permissions of /opt/atlassian/confluence recursively to my Confluence user, then starting it up - which works. 

`chown -R confluence:confluence /opt/atlassian/confluence/`

If I let Chef manage the resource and start up Confluence, it fails with the error:

```
Oct 14 13:49:31 confluence1 start-confluence.sh[25543]: Server startup logs are located in /opt/atlassian/confluence/logs/catalina.out
Oct 14 13:49:31 confluence1 start-confluence.sh[25543]: touch: cannot touch ‘/opt/atlassian/confluence/logs/catalina.out’: Permission denied
```

Here are the contents and permissions of the directories and files in question when this cookbook manages the contents:

```
[root@confluence1 confluence]# ll
total 180
drwxr-xr-x.  2 root       root  4096 Oct 14 13:49 bin
drwxr-xr-x.  3 confluence root  4096 Oct 14 13:49 conf
drwxr-xr-x. 25 root       root  4096 Jun  3  2015 confluence
drwxr-xr-x.  2 root       root  4096 Oct 14 13:49 lib
-rw-r--r--.  1 root       root 58034 Mar 23  2015 LICENSE
drwxr-xr-x.  2 root       root 36864 Oct 14 13:49 licenses
drwx------.  2 confluence root  4096 Mar 23  2015 logs
-rw-r--r--.  1 root       root  1442 Mar 23  2015 NOTICE
-rw-r--r--.  1 root       root  2291 Jun  3  2015 README.html
-rw-r--r--.  1 root       root  1202 Jun  3  2015 README.txt
-rw-r--r--.  1 root       root  6954 Mar 23  2015 RELEASE-NOTES
-rw-r--r--.  1 root       root 16682 Mar 23  2015 RUNNING.txt
drwx------.  2 confluence root  4096 Oct 14 13:49 temp
drwxr-xr-x.  2 root       root     6 Mar 23  2015 webapps
drwx------.  3 confluence root    23 Mar 23  2015 work
[root@confluence1 confluence]# ll logs/
total 188
-rw-r--r--. 1 root root 54348 Oct 14 13:46 catalina.2016-10-14.log
-rw-r--r--. 1 root root 75821 Oct 14 13:46 catalina.out
-rw-r--r--. 1 root root  2195 Oct 14 02:57 gc-2016-10-14_02-57-09.log.0.current
-rw-r--r--. 1 root root  2228 Oct 14 03:35 gc-2016-10-14_03-35-10.log.0.current
-rw-r--r--. 1 root root   578 Oct 14 03:40 gc-2016-10-14_03-40-37.log.0.current
-rw-r--r--. 1 root root   578 Oct 14 03:41 gc-2016-10-14_03-41-29.log.0.current
-rw-r--r--. 1 root root  2226 Oct 14 03:43 gc-2016-10-14_03-43-19.log.0.current
-rw-r--r--. 1 root root  4149 Oct 14 03:53 gc-2016-10-14_03-51-12.log.0.current
-rw-r--r--. 1 root root  6055 Oct 14 04:15 gc-2016-10-14_03-53-53.log.0.current
-rw-r--r--. 1 root root  2226 Oct 14 13:25 gc-2016-10-14_13-25-37.log.0.current
-rw-r--r--. 1 root root  5200 Oct 14 13:46 gc-2016-10-14_13-26-40.log.0.current
-rw-r--r--. 1 root root     0 Oct 14 02:57 host-manager.2016-10-14.log
-rw-r--r--. 1 root root     0 Oct 14 02:57 localhost.2016-10-14.log
-rw-r--r--. 1 root root     0 Oct 14 02:57 manager.2016-10-14.log
```

I believe this is because of the `ark` resource assigning the default permissions of `root:root`.

```
ark 'confluence' do
  url confluence_artifact_url
  prefix_root File.dirname(node['confluence']['install_path'])
  home_dir node['confluence']['install_path']
  checksum confluence_artifact_checksum
  version node['confluence']['version']
  owner 'root'
  group 'root'
  notifies :restart, 'service[confluence]'
end
```

https://github.com/parallels-cookbooks/confluence/blob/master/recipes/linux_standalone.rb#L39-L48

The fix would be to change the `ark` resource's `owner` to `node['confluence']['user']`. The more greedy approach would be to also change the group as well. I have tested the change and it does work. Thoughts?

```
ark 'confluence' do
  ...
  owner node['confluence']['user']
  group 'root'                      # or group node['confluence']['user']
  ...
end
```

**Comment by legal90** [comment]
That was done intentionally, according to https://confluence.atlassian.com/doc/creating-a-dedicated-user-account-on-the-operating-system-to-run-confluence-255362445.html
`logs`, `temp` and `work` - only these theree directories in installation dir should be accessible for read&write by `confluence` user.
https://github.com/parallels-cookbooks/confluence/blob/master/recipes/linux_standalone.rb#L50-L57

As we can see from your output, these directories are actually writable for `confluence`, but all the files in `logs/` dir are owned by root. It means that you've previously run confluence under root user, so root has created these files initially. That shouldn't happen in clean Confluence installation via this cookbook. 

@nickptrvc, Thank you for a report, but it's not an issue of the cookbook itself.

P.s. In your particular case, the problem could be solved by

``` console
chown -R confluence:confluence /opt/atlassian/confluence/{logs,work,temp}
```
