### ISSUE TITLE
Confluence 6 Collaborative Editing?

### ISSUE THREAD

**Issue by mrjcleaver** [sous-chefs/confluence#130]
Hi Confluence 6 adds collaborative editing and therefore requires additional rules in the proxy. 

I note the checksum permits 6.0.1 to be installed, but I didn't see proxy config changes.

Has anyone seen success?

**Comment by katbyte** [comment]
You can always disable collaborative editing after the upgrade if it does not work for you.

That aside I did not have to change anything to my local wrapper cookbook to get it working. However i did have to update my load balancer/reverse proxy server config [to get it to work](https://confluence.atlassian.com/doc/confluence-6-0-upgrade-notes-844235311.html#Confluence6.0UpgradeNotes-proxy)

**Comment by legal90** [comment]
FYI: You can override apache virtual host config with this attribute: `node['confluence']['apache2']['template_cookbook']`. Just override it in your wrapper cookbook, so you can use your custom template.

~~Unfortunately, there is no convenient way to support both of major Confluence versions in this cookbook.~~

**Comment by legal90** [comment]
I think we can handle this: #137
