### ISSUE TITLE
Is Ubuntu 16.04 supported?

### ISSUE THREAD

**Issue by mvdkleijn** [sous-chefs/confluence#131]
hey there, is 16.04 tested and working for anyone? @legal90

**Comment by legal90** [comment]
Hi @mvdkleijn,
Thanks for the question. I actually haven't tested it yet. Probably, it makes sense to add an appropriate suite to our `.kitchen.yml`.

**Comment by mvdkleijn** [comment]
I'm running some tests right now. I'm getting some issues with PostgreSQL 9.5 being installed but the cookbook (probably the postgresql cookbook, not this one) tries to run initdb for 9.3.

I'll try and further trace the issue tomorrow and let you know. Once its validated I'll do a PR to add a simple suite.

**Comment by legal90** [comment]
Great!
JFYI:  There are some hard-coded stuff In tests for PostgreSQL: https://github.com/parallels-cookbooks/confluence/blob/master/test/fixtures/cookbooks/confluence_test/recipes/postgresql.rb

**Comment by legal90** [comment]
Now the cookbook is tested under Ubuntu 16.04 and this distrib version is supported: #136
