### ISSUE TITLE
ERROR: uninitialized constant Chef::Recipe::Confluence::Helpers

### ISSUE THREAD

**Issue by phardakerffdc** [sous-chefs/confluence#132]
We have a wrapper cookbook depending on the confluence cookbook, and since upgrading to the latest version, chef-client fails with:

ERROR: uninitialized constant Chef::Recipe::Confluence::Helpers

Has anyone else experienced this issue or have any advice?

Thanks

**Comment by legal90** [comment]
Hi @comic96,
Could you please provide more context of this error log and the wrapper recipe example?

**Comment by phardakerffdc** [comment]
Hi @legal90,

sure. Below is the stack trace:

Generated at 2016-12-16 13:14:39 +0000
NameError: uninitialized constant Chef::Recipe::Confluence::Helpers
/var/chef/cache/cookbooks/confluence/recipes/linux_standalone.rb:37:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `block in include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/confluence/recipes/default.rb:23:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `block in include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/role-releng-confluence-master/recipes/confluence.rb:39:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `block in include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/role-releng-confluence-master/recipes/default.rb:11:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:256:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:454:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>'

**Our wrapper metadata.rb is as follows:**

name             'role-releng-confluence-master'
maintainer       'FinancialForce.com, Inc.'
maintainer_email 'devops@financialforce.com'
license          'All rights reserved'
description      'Installs/Configures role-releng-confluence-master'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '2.0.0'

depends 'ffdc-monitoring'
depends 'ffdc-ssl'
depends 'ffdc-volume'
depends 'confluence'
depends 'java'
depends 'fail2ban'

**Our our confluence wrapper:**

node.default['java']['jdk_version'] = '8'
node.default['java']['install_flavor'] = 'oracle'
node.default['java']['oracle']['accept_oracle_download_terms'] = true

node.default['confluence']['home_path'] = '/mnt/storage1/confluence'
node.default['confluence']['install_path'] = '/opt/atlassian/confluence'
node.default['confluence']['attachments_path'] = "#{node['confluence']['home_path']}/attachments"
node.default['confluence']['attachments_dir'] = '/mnt/storage2/attachments'
node.default['confluence']['install_type'] = 'standalone'
node.default['confluence']['version'] = '6.0.1'
node.default['confluence']['checksum'] = '444d9aa26d459ab41e42852799ffcb0ad04d1fe7471b52f8275f240860014e95'
node.default['confluence']['url'] = "#{node['confluence']['url_base']}-#{node['confluence']['version']}.tar.gz"

node.default['apache']['version'] = '2.2'
node.default['apache']['contact'] = 'devops@financialforce.com'
node.default['confluence']['apache2']['virtual_host_alias'] = 'confluence.dev.financialforce.com'
node.default['confluence']['apache2']['virtual_host_name'] = node['confluence']['apache2']['virtual_host_alias'] 
node.default['confluence']['apache2']['ssl']['certificate_file'] = "#{node['ffdc-ssl']['ssl_path']}/ffdc.cert"
node.default['confluence']['apache2']['ssl']['key_file'] = "#{node['ffdc-ssl']['ssl_path']}/ffdc.key"
node.default['confluence']['apache2']['ssl']['chain_file'] = "#{node['ffdc-ssl']['ssl_path']}/ffdc-ca.cert"

node.default['confluence']['tomcat']['ssl_port'] = '8443'
node.default['confluence']['tomcat']['keyAlias']     = 'ffdc'
node.default['confluence']['tomcat']['keystoreFile'] = "#{node['confluence']['install_path']}/confluence.jks"
node.default['confluence']['tomcat']['keystorePass'] = 'changeit'
node.default['confluence']['java_app_needs_ffdc_cert'] = true

node.default['apache']['mod_ssl']['protocol'] = 'all -SSLv2 -SSLv3 -TLSv1'
node.default['apache']['mod_ssl']['cipher_suite'] = 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK'

node.default['confluence']['jvm']['minimum_memory'] = '1024m'
node.default['confluence']['jvm']['maximum_memory'] = '2048m'
node.default['confluence']['jvm']['maximum_permgen'] = '320m'
node.default['confluence']['jvm']['java_opts'] = ''
node.default['confluence']['jre_home'] = ENV['JAVA_HOME']
	
include_recipe 'java'
include_recipe 'ffdc-ssl'
include_recipe "confluence"
include_recipe "confluence::#{node['os']}_#{node['confluence']['install_type']}"
include_recipe 'confluence::tomcat_configuration'
include_recipe 'confluence::apache2'
include_recipe 'confluence::configuration'
include_recipe 'postgresql::config_pgtune'

java_app_needs_ffdc_cert = node['confluence']['java_app_needs_ffdc_cert']
confluence_install_path = node['confluence']['install_path']

It seems to be a recipe compile error when trying to include "confluence"

Many thanks

**Comment by phardakerffdc** [comment]
@legal90 any thoughts about this? Thanks!

**Comment by phardakerffdc** [comment]
Please ignore this, it was a problem on our side. Apologies for bothering you with this!
