### ISSUE TITLE
Just a question on file ownership

### ISSUE THREAD

**Issue by rylectro** [sous-chefs/confluence#144]
Is ownership not important on the install_path directories and files? 

I see they are mostly root:root except a select few modified in the configuration.rb.

**Comment by legal90** [comment]
Hi @rylectro,
According to [these recommendations](https://confluence.atlassian.com/doc/creating-a-dedicated-user-account-on-the-operating-system-to-run-confluence-255362445.html), there are only 3 sub-dirs in the `install_path`, which should be writable for `confluence` user:
- logs
- temp
- work

**Comment by rylectro** [comment]
Perfect thanks! In case anyone wants this 

> %w[ /logs /temp /work ].each do |path|
>   directory File.join(node['confluence']['install_path'],"#{path}") do
>     owner node['confluence']['user']
>     mode '0755'
> end

**Comment by legal90** [comment]
Yeah, correct :)
https://github.com/parallels-cookbooks/confluence/blob/7ecb3d8/recipes/linux_standalone.rb#L50-L57

**Comment by rylectro** [comment]
++
