### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by heaven** [sous-chefs/confluence#16]
Hi, was trying to upgrade from 5.3 to 5.6.3, specified the version and check sum, the recipe does download the installer but does not run it. I mean this code:

``` ruby
execute "Installing Confluence #{node['confluence']['version']}" do
  cwd Chef::Config[:file_cache_path]
  command "./atlassian-confluence-#{node['confluence']['version']}-#{node['confluence']['arch']}.bin -q -varfile atlassian-confluence-response.varfile"
  creates node['confluence']['install_path']
end
```

doesn't run if /opt/atlassian exists.

But even if I move /opt/atlassian to /opt/atlassian.back it creates new users, like confluence[n+1] and the installation fails.

**Comment by gsreynolds** [comment]
#40 should close this

**Comment by legal90** [comment]
It was fixed by https://github.com/bflad/chef-confluence/pull/33
