### ISSUE TITLE
Call for maintainer

### ISSUE THREAD

**Issue by anuriq** [sous-chefs/confluence#162]
Hi all.

Unfortunately, Parallels team including me does not have enough resources to support this cookbook. To avoid slowdown for Confluence users using Chef automation, we came to decision to hand over this cookbook to someone who has required knowledge and sufficient resources.

If you are interested, please reply here, or contact me directly.

**Comment by gsreynolds** [comment]
Hi @anuriq, might be worth flagging as [available for adoption](https://supermarket.chef.io/available_for_adoption) on Chef Supermarket as well.

**Comment by anuriq** [comment]
@gsreynolds did it

**Comment by scottmeuth** [comment]
Removing general support for mysql from the cookbook appears to make it work in the current version, grant it, this is a stop gap.

**Comment by anuriq** [comment]
@scottmeuth hi, not sure i understood

**Comment by shoekstra** [comment]
Hi there!

I came across this cookbook and saw it is looking for new maintainers - perhaps this is something that the [Sous Chefs](http://sous-chefs.org/) could assist with.  

We generally look to pick up cookbooks that are actively used by the Chef community but are looking for new maintainers to keep them alive.  We help triage issues, review/accept PRs and, when necessary, update cookbooks to work with current supported Chef versions when the previous maintainers no longer have the time or focus

Hope this answers your call for help!  If you want to know about the Sous Chefs, please feel free to get in touch or chat to us [on Slack](https://chefcommunity.slack.com/messages/sous-chefs).

Stephen

**Comment by damacus** [comment]
That's brilliant.

Would you be able to make a PR onto a new page or something?

**Comment by anuriq** [comment]
Hi @shoekstra 
I am really interested. But how do I get an invite for Chef Community Slack?

**Comment by damacus** [comment]
Hey @anuriq

http://community-slack.chef.io/ to register

**Comment by shoekstra** [comment]
@anuriq - once you've signed up feel free to get in touch with me or @damacus directly or via the #sous-chefs channel.

**Comment by xorima** [comment]
Hi, 

I have opened a PR for being added as a maintainer to this cookbook and will be looking through all opened issues shortly. 

https://github.com/sous-chefs/terraform-github-org/pull/127
