### ISSUE TITLE
Apache proxy_wstunnel module needed for synchrony

### ISSUE THREAD

**Issue by cadalso** [sous-chefs/confluence#163]
At https://github.com/parallels-cookbooks/confluence/blob/master/templates/default/web_app.conf.erb#L61 WebSockets is used. However, at https://github.com/parallels-cookbooks/confluence/blob/master/recipes/apache2.rb proxy_wstunnel is not included.

**Comment by cadalso** [comment]
I solved this issue by adding this to a wrapping cookbook. 
```
include_recipe 'confluence::default'
apache_module "proxy_wstunnel"

```

**Comment by anuriq** [comment]
Hi @cadalso 
As you may have seen, this cookbook is looking for maintainer, so not actively supported. I am glad, that you found a workaround.

**Comment by damacus** [comment]
Closing as fixed with a work around.
