### ISSUE TITLE
Installer Ignores home_path

### ISSUE THREAD

**Issue by identifystation** [sous-chefs/confluence#17]
The confluence installer (at least 5.6.3) sets the confluence user's home directory to /home/confluence.  This causes the test looking for it to be set to home_path to fail.

**Comment by esciara** [comment]
@abrown-sg could you give more details please?

**Comment by identifystation** [comment]
So regardless of what home_path attribute is passed to this cookbook,  the confluence installer will always make the confluence user's home directory /home/confluence.

I'm passing in the following:

``` ruby
default['confluence']['version'] = '5.6.3'
default['confluence']['user'] = 'confluence'
default['confluence']['home_path'] = '/var/atlassian/application-data/confluence'
```

But the test fails because the home directory created for the user doesn't match home_path.

```
Failure:
recipe::confluence::linux_installer#test_0001_has confluence user [/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/minitest-chef-handler-1.0.3/lib/minitest-chef-handler/resources.rb:48]:
The user does not have the expected home.
--- expected
+++ actual
@@ -1 +1 @@
-"/var/atlassian/application-data/confluence"
+"/home/confluence"
```

**Comment by esciara** [comment]
@abrown-sg : If you provide a failing ServerSpec test for this, I will help on how to sort it out.

**Comment by legal90** [comment]
@abrown-sg Is this issue still exist? 
And could you please tell how do you run these tests?

**Comment by identifystation** [comment]
Hey all, unfortunately I left the job where I was experiencing this issue a while ago, and don't remember the exact specifics anymore. Probably safe to close if nobody else is experiencing the issue.

**Comment by legal90** [comment]
> Probably safe to close if nobody else is experiencing the issue.

OK, closed. Seems like it's already fixed
