### ISSUE TITLE
Undefined node attribute or method `|' on `node'. To set an attribute, use `|=value' instead.

### ISSUE THREAD

**Issue by Idun0** [sous-chefs/confluence#170]
### Chef-client version
12.19.36

         NoMethodError
         -------------
         Undefined node attribute or method `|' on `node'. To set an attribute, use `|=value' instead.
         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/confluence/recipes/apache2.rb:26:in `from_file'
           /tmp/kitchen/cache/cookbooks/confluence/recipes/default.rb:27:in `from_file'
           /tmp/kitchen/cache/cookbooks/tm_confluence/recipes/_confluence.rb:80:in `from_file'
           /tmp/kitchen/cache/cookbooks/tm_confluence/recipes/default.rb:10:in `from_file'
         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/confluence/recipes/apache2.rb:
          19:  if node['apache'].attribute?('listen_ports')
          20:    # Compatibility with cookbook 'apache' < 3.2.0
          21:    node.default['apache']['listen_ports'] |= [
          22:      node['confluence']['apache2']['port'],
          23:      node['confluence']['apache2']['ssl']['port'],
          24:    ]
          25:  else
          26>>   node.default['apache']['listen'] |= [
          27:      "*:#{node['confluence']['apache2']['port']}",
          28:      "*:#{node['confluence']['apache2']['ssl']['port']}",
          29:    ]
          30:  end
          31:
          32:  include_recipe 'apache2'
          33:  include_recipe 'apache2::mod_proxy'
          34:  include_recipe 'apache2::mod_proxy_http'
          35:  include_recipe 'apache2::mod_ssl'
         Platform:
         ---------
         x86_64-linux

Am i Missing something simple here, im not able to get a clean instance running

**Comment by xorima** [comment]
Hi,
We are only supporting versions of chef that are supported by chef, so currently this is 13+

However if you are able to give me some sample code I will see if we can get this fixed, I know that apache2 was released recently and went to support of Chef13+ (https://github.com/sous-chefs/apache2/blob/master/metadata.rb) so it would be best if you migrate to Chef13/14 asap,

Thanks

Xorima

**Comment by damacus** [comment]
Closing this due to it being a Chef 12.19 bug. If you are able to reopen and fix this please do so!
