### ISSUE TITLE
chef-solo run fails with java-ark resource not found.

### ISSUE THREAD

**Issue by shishir** [sous-chefs/confluence#2]
Fails on linux_installer recipe at line 71. PFA screenshot of the source code.

![screen shot 2014-01-01 at 3 55 09 pm](https://f.cloud.github.com/assets/21552/1829537/190a306c-72cf-11e3-8128-862a6495c26e.png)

**Comment by bflad** [comment]
Ah, currently the cookbook is expecting the usage of the java cookbook as
well. I made a similar fix in the stash cookbook to change that resources()
to just the string, which I believe fixes the issue as well. I'll try to
get the fix in for you later today.

Brian Flad

**Comment by bflad** [comment]
Please let me know if 1.7.1 doesn't resolve your issue. Thanks!
