### ISSUE TITLE
MySQL server's default character set not set to UTF8 

### ISSUE THREAD

**Issue by esciara** [sous-chefs/confluence#21]
This issue is close to issue #14.

According to [Database Setup For MySQL Documentation Page, Step 3](https://confluence.atlassian.com/display/CONF55/Database+Setup+For+MySQL#DatabaseSetupForMySQL-Step3.ConfigureMySQLServer), point 2, the default character set for the MySQL server should be set to `utf8` as following and is not :

```
[mysqld]
...
character-set-server=utf8
collation-server=utf8_bin
...
```

**Comment by esciara** [comment]
Using the [`enable_utf8` parameter in the currently used `mysql` cookbook](https://github.com/opscode-cookbooks/mysql/tree/b1c9c3064c9889795b8868f0f1a3cc2425371f58#example) (`v5.6.1` st the time of this writing) [adds the following in the `my.cnf` file](https://github.com/opscode-cookbooks/mysql/blob/b1c9c3064c9889795b8868f0f1a3cc2425371f58/templates/default/5.5/my.cnf.erb#L38):

```
[mysqld]
...
collation-server               = utf8_general_ci
init-connect                   = 'SET NAMES utf8'
character-set-server           = utf8
...
```

Here are some insight on the [differences between `utf8_bin` and `utf8_general_ci`](http://board.phpbuilder.com/showthread.php?10344217-Difference-between-utf8_general_ci-and-utf8_bin).

**Comment by esciara** [comment]
Looking at differences between `utf8_bin` and `utf8_general_ci` in the previously mentioned link, it would be very useful to allow for `utf8_general_ci` as an option as it is far more suitable than `utf8_bin` in quite a few cases (or at least, at my workplace, it is).

**Comment by legal90** [comment]
I'm gonna close this issue since it is very old and the info mentioned above is outdated. Feel free to file a new issue with details if it is still actual
