### ISSUE TITLE
Should ServerName be the FQDN?

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#34]
Should these be flipped?
https://github.com/bflad/chef-confluence/blob/master/attributes/default.rb#L35-L36

My understanding is that the ServerName is intended to be the FQDN (we set ServerName from virtual_host_alias in the apache conf)

**Comment by legal90** [comment]
@patcon thanks!
Actually, according to Apache documentation, `ServerName` should be set to FQDN while `ServerAlias` can be just a hostname.

cc:\ @linc01n, I suppose it should be done in chef-stash as well.

**Comment by patcon** [comment]
Cool :) This might break people's stuff, right? Major version bump?

**Comment by patcon** [comment]
See my comment in the commit @dc6c6aa, but I think this may have broken apache redirects (?)

**Comment by patcon** [comment]
As a correction, it's no the apache settings, but the server.xml proxy settings that need to be synced with the referenced change in the commit

**Comment by gsreynolds** [comment]
It will need to be flipped here as well: https://github.com/bflad/chef-confluence/blob/master/templates/default/server.xml.erb#L25
to
`proxyName="<%= node['confluence']['apache2']['virtual_host_name'] %>"`

(I wrote a basic wrapper cookbook for https://github.com/juliandunn/jira that setup an Apache proxy, that was borrowed partially from this cookbook, and had to make the above change in what I'd copied from here.)

(Also afterwards noticed there is a https://github.com/bflad/chef-jira/ cookbook that's seemingly inactive. @patcon @legal90, any plans to make similar efforts with that? Happy to help out.)

**Comment by patcon** [comment]
(aside: @gsreynolds might be better using bflad's jira cookbook, even though it doesn't have the canonical namespace: https://github.com/bflad/chef-jira)
