### ISSUE TITLE
Update mysql cookbook to 6.x

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#36]
Any objection to my upgrading the metadata mysql cookbook requirement to `~> 6.0` ? Shouldn't be too much work

**Comment by patcon** [comment]
fwiw, I'm not using the mysql database type mysql, but i have another cookbook in my chef repo that has the "~> 6.0" constraint, so it's keeping them from co-existing happily (even though I don't care about the mysql cookbook for confluence. Couple options:
1. upgrade the mysql cookbook.
2. move mysql and postgresql to `suggests` in metadata rather than `depends`
3. take the constraint out of metadata and fail only in the `mysql` case by checking the cookbook version in the recipe:
   https://stackoverflow.com/questions/13689811/get-deployed-cookbook-version

**Comment by legal90** [comment]
Implemented by #50
