### ISSUE TITLE
vagrant-berkshelf plugin to be deprecated

### ISSUE THREAD

**Issue by esciara** [sous-chefs/confluence#4]
Hi,

As of Tuesday, January 28th the [Berkshelf core team announced the future deprecation and retirement of the vagrant-berkshelf plugin](https://sethvargo.com/the-future-of-vagrant-berkshelf/). In his [Chef with Berkshelf tutorial](http://misheska.com/blog/2013/06/16/getting-started-writing-chef-cookbooks-the-berkshelf-way/), Mischa Taylor recommends to switch to test-kitchen for development as well as integration. good idea?...

Em

**Comment by bflad** [comment]
Wasn't that hard to convert the Vagrantfile into a .kitchen.yml. Left Vagrantfile there in case anyone still uses it. Closed via: https://github.com/bflad/chef-confluence/commit/11cc96f7211cbcf21b7ef7288838efc1203db5fa
