### ISSUE TITLE
Allow config of database via tomcat datasource

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#42]
I'm still new to Java-land, but this would seem helpful in making the wizard a little more straightforward.
- https://confluence.atlassian.com/display/CONFEAP/Configuring+a+PostgreSQL+Datasource+in+Apache+Tomcat
- https://confluence.atlassian.com/display/CONFEAP/Configuring+a+MySQL+Datasource+in+Apache+Tomcat

Seems then there's no need to copy user and database names and password into the wizard.

Any objections or concerns from those who are more veteran to tomcat?

**Comment by gsreynolds** [comment]
Hi,

For reference, this is how the JIRA cookbook (that Chef used to maintain for their JIRA install, and that has the JIRA namespace on Supermarket), does it: 
https://github.com/juliandunn/jira/blob/master/templates/default/dbconfig.xml.erb
https://github.com/juliandunn/jira/blob/master/recipes/local_database.rb#L53

The setup wizard skips the database config when that's configured. This is presumably similar for confluence, though I haven't gotten into that yet.

**Comment by gsreynolds** [comment]
Possibly a useful reference here: https://github.com/jenkins-infra/confluence/blob/master/confluence/site/conf/server.xml#L16

**Comment by legal90** [comment]
I'm new with that staff too, but Atlassian recommends to use the direct JDBC connection (e.q. the current approach), over the datasource configuration on the Tomcat's side:

> There is no much of a difference between terms of performance, we usually recommend JDBC over JNDI because the default Tomcat libraries may not be optimized for Atlassian applications.
> Using direct JDBC is the standard method when installing Confluence which also offer you more configuration option regarding the connection pool size and timeout into the <Confluence Home>\confluence.cfg.xml file.

https://answers.atlassian.com/questions/8629689/datasource-vs-jdbc

P.s. By the way, PostgreSQL JDBS driver is bundled with Confluence, and makes JDBC configuration a little bit easier:

> If you are using a direct JDBC connection, you do not need to download or install the drivers that are bundled. If you are connecting via a datasource, or if you are using a database whose driver is not bundled, you will need to download and install the drivers manually.

https://confluence.atlassian.com/doc/database-jdbc-drivers-171742.html

**Comment by legal90** [comment]
Anyway, if there will be some other opinions - we  are always open for Pull-Requests! ;-)

**Comment by patcon** [comment]
I wouldn't take their recommendation too seriously, as Atlassian's inattentiveness to config management concerns is an ongoing issue with the people maintaining config management offerings. Basically, they will make recommendations without any consideration of our needs, so I think we can disregard them in cases like this, especially when they acknowledge "not much difference" :)

And in order for the "more configurability" thing to apply to us, we'd need to get `confluence.cfg.xml` into a template, which I don't think is something we could easily do.

Anyhow, my two cents! I'd still like to see this added, as I'm currently needing to mangle `confluence.cfg.xml` with the `xml_edit` resource when I do a restore from backup (via a wrapper cookbook recipe). It feel pretty gross when using JDBC :)

**Comment by legal90** [comment]
@patcon But switching to datasource doesn't provide "more configurability", because  `confluence.cfg.xml` still contains Server ID and License, so it can't be covered by the template.

**Comment by patcon** [comment]
Not sure I understand. It (datasource and its separate db config file) lets the username/password/(other db properties) be set programmatically without messing around with an xml file that the wizard wants to own (ie. that is hard to store as a template)

**Comment by mrjcleaver** [comment]
When using Java Melody, a popular diagnostics tool, you have to use a Data Source to get any depth of understanding about what the database is doing.

**Comment by mrjcleaver** [comment]
As such I think we should open this again.
