### ISSUE TITLE
Bigfix for previous fqdn/hostname swap

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#44]
See: https://github.com/bflad/chef-confluence/issues/34

**Comment by legal90** [comment]
Hm... There is no bugfix attached. Did you want to send a pull request?

**Comment by gsreynolds** [comment]
See my comment on https://github.com/bflad/chef-confluence/issues/34, minor change is required in server.xml:
`proxyName="<%= node['confluence']['apache2']['virtual_host_alias'] %>"`
to
`proxyName="<%= node['confluence']['apache2']['virtual_host_name'] %>"`

**Comment by patcon** [comment]
heh, it was just placeholder :) but @gsreynolds' solves it, so I'll close
