### ISSUE TITLE
Ensure database cookbook deps satisfied if database type used

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#51]
This was alluded to here: https://github.com/bflad/chef-confluence/pull/43#issuecomment-137343440

Basically, we're not strictly locking to a version constraint for DB cookbooks as they might not be required, depending on DB type. But we probably want to throw a warning or fail out of the chef run if that DB type is actually used and the chef run is using an improper version

`chef-sugar` seemingly has a semantic core function to compare versions:
https://github.com/sethvargo/chef-sugar#core-extensions

And this should get the cookbook version easily:
http://stackoverflow.com/a/13710498

**Comment by legal90** [comment]
We've added these cookbook to dependencies (https://github.com/parallels-cookbooks/confluence/pull/43#issuecomment-137343440), so this task could be closed now.
