### ISSUE TITLE
Move helpers into "Confluence" module

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#55]
Right now, we've got the settings helper created with:

``` rb
settings = merge_confluence_settings
```

This is great when we're using it in the confluence cookbook, but when someone has a wrapper cookbook where it's also being used, it's not very obvious where it's coming from.

@bflad's stash cookbook seems to have a better approach:
https://github.com/bflad/chef-stash/blob/master/recipes/database.rb#L1

I personally feel this would give me clarity, and a hint to the fact that some noteworthy merging is happening:

``` rb
settings = Confluence.merged_settings(node)
```

Let's do this? Thoughts?

**Comment by legal90** [comment]
@patcon I've made it recently just in order to follow the recommendations from Chef how libraries should look like:
https://www.chef.io/blog/2014/03/12/writing-libraries-in-chef-cookbooks/
https://docs.chef.io/libraries.html
I was also inspired by examples from `mysql` , `postgresql` cookbooks.

Actually, these helpers methods are designed for usage in the same cookbook. There is no need to call `merge_confluence_settings` in wrapper cookbooks.

**Comment by patcon** [comment]
> Actually, these helpers methods are designed for usage in the same cookbook. There is no need to call merge_confluence_settings in wrapper cookbooks.

heh. i beg to differ :) I am calling them in a wrapper cookbook (for manipulating config files, doing restore from backup, etc), which is totally reasonable, right? otherwise the node object might differ from the settings hash, and attributes in the wrapper wouldn't match the actual cookbook

**Comment by patcon** [comment]
For example, if I want to talk to the database in my wrapper cookbook, I need to recreate the logic in here, including loading the merged settings hash:
https://github.com/bflad/chef-confluence/blob/master/recipes/database.rb

I'd much rather replace all the repetition with DRYness:

``` rb
# my_confluence/recipes/restore.rb
settings = Confluence.merge_confluence_settings

postgresql_database settings['database']['name'] do
  connection Confluence.database_connection
  owner settings['database']['user']
  action [:drop, :create]
end
```

Is this unreasonable?

**Comment by bflad** [comment]
I think it's reasonable that this cookbook provides external cookbooks a
method for retrieving the finished product of determining the settings just
like the cookbook internally uses so they don't have to reinvent the wheel.
