### ISSUE TITLE
Generate `database_connection` in helper library

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#56]
The `database_connection` hash is generated on the fly in `confluence::database`:
https://github.com/bflad/chef-confluence/blob/master/recipes/database.rb#L22-L43

I'm needing to regenerate this in a wrapper cookbook in order to create a `my_confluence::restore` recipe customized to our infra. It would be nice if the hash was available via a library method like `Confluence.database_connection(node)`.

Thoughts?

(This probably depends on #55 happening first)

**Comment by legal90** [comment]
Hm... I think It might be reasonable to remove database management from this cookbook at all.
On the one hand it means that cookbook usage for development environments will be complicated a little bit. So, users will have to take care about database management in their wrappers.

But on other hand it will allow users to configure database by any way they want. It make sense for production usage.

@bflad Any thoughts?

P.s. As you remember, in `mysql` cookbook there was a similar decision - they got rid of `mysql_chef_gem` management, so now this cookbook became more stable, reliable and just works fine :)

**Comment by patcon** [comment]
I'm not sure that's an analogous situation with the mysql cookbook. That was to resolve a compilation issue with the mysql2 gem.

I don't see any evidence in the community of database management being removed from application cookbooks, and I respectfully disagree that it's a good path.

EDIT: But yes, it would be great if basic database setup were easily bypassed :)

**Comment by bflad** [comment]
I think there could potentially be some slight value in creating a separate
but community supported cookbooks that bridge between the application and
database itself mostly from the sense of removing dependencies (see Docker
apt repo vs Docker yum repo cookbooks. In our case if you use postgres, you
wouldnt need to pull MySQL dependencies when you don't need or care about
them. The caveat is the development and operations overhead of explicitly
documenting and requiring the extra cookbook and environment configuration
for it.

Personally I'm not sure there's a winning argument either way. In an ideal
world  we'd be provided a way to set external cookbook dependencies per
actually used recipe and not at the cookbook level as a whole.

For the above management question, simple attribute flag to "manage
database myself" seems reasonable? For the original question it shouldn't
be too crazy to allow outside resources access to the stash database info
via some library method.
