### ISSUE TITLE
Add a sponsorshop or supporter section to README

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#58]
Hey guys,

I'm working for a client, Blended Perspectives, that has been very generous with allowing me to contribute to this cookbook. I was wondering whether it might be possible to add a section recognizing organization-level contributions.

``` md

### Sponsors

Development of this cookbook has been generously supported in part by the code contributions of the following organizations:

* [University of Pennsylvania](http://www.upenn.edu/)
* [Parallels Inc.](https://www.parallels.com)
* [Blended Perspectives Inc.](http://www.blendedperspectives.com/)
```

cc: @mrjcleaver

**Comment by bflad** [comment]
I'd +1 this

**Comment by patcon** [comment]
Cool. Incoming PR :)
