### ISSUE TITLE
[meta] atlassian_application library cookbook?

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#76]
I'm sure you guys have thought about this as well, but bflad started all these repos with a very consistent style, and it seems that atlassian has more and more strived to make the converge on a single way of running all its apps.

I haven't worked extensively with any cookbooks besides confluence and jira, but I thought I'd start this issue to at least discuss the idea of working toward this :) Maybe it's a silly idea and too much abstraction, but it seems that we're porting almost every change between the two cookbooks so far :)

Eager to hear from folks who've worked with more atlassian apps

cc: @bflad @legal90 @ramonskie @gsreynolds @mvdkleijn @linc01n

**Comment by mvdkleijn** [comment]
We work with the entire Atlassian suite and I am not detecting much convergence. There is some (maybe one can even say a lot) between Confluence and JIRA, but the rest of their suite is still quite different. Crowd for example isn't even being built using Maven which makes it difficult to reliably auto-detect its version.

Personally I say: not enough convergence right now to even consider it.

**Comment by patcon** [comment]
Ah, ok good to know :) Thanks @mvdkleijn!
