### ISSUE TITLE
Cookbook on opscode supermarket is outdated

### ISSUE THREAD

**Issue by computerlyrik** [sous-chefs/confluence#85]
or inconsistent with "releases" here on github...

**Comment by legal90** [comment]
@computerlyrik Yes, it is.
We are working on 2.0.0 release(https://github.com/parallels-cookbooks/confluence/issues/53#issuecomment-157205422), which has a bunch of changes in comparison with the current version on supermarket

**Comment by computerlyrik** [comment]
I see. This is why i am using the git version as submodule right now.

Nevertheless - i think this issue should stay open, until it is in a 'fixed' state.

**Comment by legal90** [comment]
> Nevertheless - i think this issue should stay open, until it is in a 'fixed' state.

We already have this one: https://github.com/parallels-cookbooks/confluence/issues/53
