### ISSUE TITLE
Get rid of `node['fqdn']` usage?

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#88]
It's apparently broken on some systems, and so the brokenness of chef reflects that intentionally. 

Context: https://github.com/chef/ohai/pull/648#issuecomment-161050543

We could fail out if not explicitly defined, and strip out its usage as it's not recommended?

**Comment by lamont-granquist** [comment]
`node[:fqdn] || node[:machinename] || node[:hostname]` is pretty battle-tested and is what chef-client uses internally to guess the node name:

https://github.com/chef/chef/blob/4d35de670c9d54ad3b672e668672ba3256e2aef8/lib/chef/client.rb#L565-L566
