### ISSUE TITLE
Ensure crowd.properties not world-readable

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#90]
Haven't tested whether this confuses confluence, but since there's a password in that file, we should probably see if we can restrict access to the confluence user :)

**Comment by patcon** [comment]
Actually, unsure whether this is part of the thread model of a server running an atlassian app... so feel free to close if you don't think it's warranted :)

**Comment by legal90** [comment]
We don't manage this file in this cookbook, so it is created automatically by Confluence Setup Wizard (initial setup via web). 
@patcon Thank you for opening that. I understand that permissions are really important, but I don't think that we have to do it by our cookbook, at least in the current cookbook implementation.

Probably, it will make sense in the future, when it will be possible to manage `crowd.properties` via cookbook.
