### ISSUE TITLE
Sync repo and tags with supermarket

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#96]
- Git tag for v1.8.0 exists
- metadata.rb version says 1.7.1
- supermarket site only released up to 1.7.1
- changelog says x.y.z pending

Can we clean this up? I forget if i've mentioned it, but `stove` is great for preventing this sort of thing :)

**Comment by patcon** [comment]
fwiw, we should probably either sync the changelog with the rogue 1.8.0 tag's features, or just delete the tag and release fresh today

**Comment by patcon** [comment]
Also, I'm happy to come on as release manager if this all seems more tedious that you care to stress about :)

**Comment by legal90** [comment]
Thank you for follow up! I've just removed the tag 1.8.0 to avoid the misunderstanding.
And let's finally cut the 2.0.0 as it is at the moment. :)

@patcon 
It would be great if you help to actualize a changelog. Could you please prepare a PR for it? 
If there are some unclear changes feel free to skip them, so I will describe them by myself. Thanks!

**Comment by patcon** [comment]
Ah, sorry, I didn't realize I was the only one adding entries. Hm. I definitely don't have time for that today, and am going on vacation for a few weeks, so I don't think I'm useful on that front atm :(

EDIT: Would be great if the release wasn't held up on the changelog though :)

**Comment by legal90** [comment]
OK, no problem. I'll do it.

**Comment by legal90** [comment]
Done: https://supermarket.chef.io/cookbooks/confluence/versions/2.0.0
Changelog has been also updated
